package com.cherokeelessons.cll2ev1;

import java.nio.charset.StandardCharsets;

import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.utils.Json;
import com.cherokeelessons.cll2ev1.models.CardData;
import com.cherokeelessons.cll2ev1.models.GameCard;
import com.cherokeelessons.cll2ev1.screens.LearningSession;
import com.cherokeelessons.deck.CardStats;
import com.cherokeelessons.deck.Deck;
import com.cherokeelessons.deck.ICard;
import com.cherokeelessons.util.SlotFolder;

public class StartSession implements Runnable {
	private static final String ACTIVE_CARDS = CLL2EV1.ACTIVE_CARDS;
	private final AbstractGame game;
	private final int session;
	private final Json json = new Json();

	public StartSession(AbstractGame game, int session) {
		this.game = game;
		this.session = session;
	}

	@Override
	public void run() {
		FileHandle activeCardsJson = SlotFolder.getSlotFolder(session).child(ACTIVE_CARDS);
		String tmp;
		try {
			tmp = activeCardsJson.readString(StandardCharsets.UTF_8.name());
		} catch (Exception e) {
			tmp = "";
		}
		String[] jsonCardsStats = tmp.split("\n");
		/*
		 * Always create a fresh deck by copying (cloning) cards from the CSV
		 * master deck. If we have stats that don't match a card in the fresh
		 * deck they will be ignored and lost at next save. The match up is done
		 * by "card id" which is the minimal amount of uniqueness to match up as
		 * generated by the CardData object. Being sure to set all stats to
		 * "never shown/correct".
		 */
		Deck<CardData> masterDeck = new Deck<CardData>();
		for (GameCard card : ((CLL2EV1) game).cards) {
			ICard<CardData> copy = card.copy();
			copy.resetStats();
			copy.resetTriesRemaining();
			copy.getCardStats().setPimsleurSlot(0);
			masterDeck.add(copy);
		}
		Deck<CardData> activeDeck = new Deck<CardData>();
		/*
		 * The json card stats data aren't stored directly as a single json
		 * object in a list to reduce memory requirements for serialization and
		 * deserialization. Each valid set of stats indicates a card already
		 * "in play". Update each such card with the saved stats and move each
		 * one into the "active deck".
		 */
		for (String jsonCardStats : jsonCardsStats) {
			if (jsonCardStats.trim().isEmpty()) {
				continue;
			}
			if (!jsonCardStats.contains("\t")) {
				continue;
			}
			String[] txtStats = jsonCardStats.split("\t");
			if (txtStats[0].trim().isEmpty()) {
				continue;
			}
			if (txtStats[1].trim().isEmpty()) {
				continue;
			}
			String id = txtStats[0];
			copyStatsLoop: for (ICard<CardData> card : masterDeck.getCards()) {
				if (!id.equals(card.id())) {
					continue;
				}
				CardStats stats = json.fromJson(CardStats.class, txtStats[1]);
				card.setCardStats(stats);
				// move this "in play" card into the active deck. Being sure to
				// set all stats to "never shown/correct".
				card.resetStats();
				card.resetTriesRemaining();
				card.getCardStats().setPimsleurSlot(0);
				activeDeck.add(card);
				break copyStatsLoop;
			}
		}
		game.setScreen(new LearningSession(game, session, masterDeck, activeDeck));
	}
}